"""create talent_media

Revision ID: 589f21e2e545
Revises: 9b935406e6be
Create Date: 2026-05-20 09:03:24.895806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589f21e2e545'
down_revision: Union[str, Sequence[str], None] = '9b935406e6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talent_media',
    sa.Column('talent_media_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('media_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('stored_file_name', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('view_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("media_type IN ('PHOTO','MOVIE')", name='ck_talent_media_media_type'),
    sa.ForeignKeyConstraint(['account_id'], ['talent_master.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('talent_media_id')
    )
    op.create_index('ix_talent_media_account_id_sort_order', 'talent_media', ['account_id', 'sort_order'], unique=False)
    op.create_index('uq_talent_media_one_main_per_account', 'talent_media', ['account_id'], unique=True, postgresql_where=sa.text('is_main'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_talent_media_one_main_per_account', table_name='talent_media', postgresql_where=sa.text('is_main'))
    op.drop_index('ix_talent_media_account_id_sort_order', table_name='talent_media')
    op.drop_table('talent_media')
    # ### end Alembic commands ###
