"""create admin_master

Revision ID: 5ca70ff5abba
Revises: 
Create Date: 2026-05-20 05:55:01.162927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ca70ff5abba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_master',
    sa.Column('admin_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('role_code', sa.String(length=20), nullable=False),
    sa.Column('permission_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("role_code IN ('SUPER', 'OPERATOR', 'CS')", name='ck_admin_master_role_code'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_master')
    # ### end Alembic commands ###
