"""add talent_master extra fields (career_years, body/face/visual, education, weight_range)

Revision ID: 7863df88d288
Revises: 589f21e2e545
Create Date: 2026-05-29 14:34:32.254373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7863df88d288'
down_revision: Union[str, Sequence[str], None] = '589f21e2e545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talent_master', sa.Column('weight_range', sa.String(length=20), nullable=True))
    op.add_column('talent_master', sa.Column('body_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('talent_master', sa.Column('face_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('talent_master', sa.Column('visual_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('talent_master', sa.Column('education_level', sa.String(length=20), nullable=True))
    op.add_column('talent_master', sa.Column('education_major', sa.String(length=100), nullable=True))
    op.add_column('talent_master', sa.Column('career_years', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talent_master', 'career_years')
    op.drop_column('talent_master', 'education_major')
    op.drop_column('talent_master', 'education_level')
    op.drop_column('talent_master', 'visual_keywords')
    op.drop_column('talent_master', 'face_type')
    op.drop_column('talent_master', 'body_type')
    op.drop_column('talent_master', 'weight_range')
    # ### end Alembic commands ###
