"""create role_master + remove admin permission_json

Revision ID: 933988511f0c
Revises: a9a4c7007f6a
Create Date: 2026-05-20 07:46:10.366707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '933988511f0c'
down_revision: Union[str, Sequence[str], None] = 'a9a4c7007f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'role_master',
        sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('account_type', sa.String(length=20), nullable=False),
        sa.Column('role_code', sa.String(length=30), nullable=False),
        sa.Column('display_name', sa.String(length=100), nullable=False),
        sa.Column('permission_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.CheckConstraint("account_type IN ('ADMIN', 'TALENT', 'AGENCY')", name='ck_role_master_account_type'),
        sa.PrimaryKeyConstraint('role_id'),
        sa.UniqueConstraint('account_type', 'role_code', name='uq_role_master_type_code'),
    )

    # ────────── 시드 데이터 5행 ──────────
    # permission_json.menu 의 키는 frontend 의 코드 기반 메뉴 정의와 매칭됨.
    # "*" 와일드카드는 모든 메뉴 허용.
    op.execute("""
        INSERT INTO role_master (account_type, role_code, display_name, permission_json, description)
        VALUES
        ('ADMIN',  'SUPER',    '최고관리자',
            '{"menu": ["*"]}'::jsonb,
            '모든 시스템 메뉴/기능 접근'),
        ('ADMIN',  'OPERATOR', '운영자',
            '{"menu": []}'::jsonb,
            '운영 메뉴 — 추후 정의'),
        ('ADMIN',  'CS',       '고객지원',
            '{"menu": []}'::jsonb,
            '고객지원 메뉴 — 추후 정의'),
        ('TALENT', 'DEFAULT',  '연기자',
            '{"menu": ["profile","portfolio","applications","recommended","ai_report","settings"]}'::jsonb,
            '연기자 기본 메뉴'),
        ('AGENCY', 'DEFAULT',  '에이전시',
            '{"menu": ["ai_recommend","talent_explore","casting_register","casting_active","applicants","favorites","company_settings"]}'::jsonb,
            '에이전시 기본 메뉴 — 추후 OWNER/MANAGER/STAFF 등 sub-role 추가 예정')
        ;
    """)

    op.drop_column('admin_master', 'permission_json')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_master', sa.Column('permission_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('role_master')
    # ### end Alembic commands ###
