"""create talent_master + agency_master + agency_member

Revision ID: 9b935406e6be
Revises: 933988511f0c
Create Date: 2026-05-20 08:41:57.523098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b935406e6be'
down_revision: Union[str, Sequence[str], None] = '933988511f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_master',
    sa.Column('agency_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agency_name', sa.String(length=200), nullable=False),
    sa.Column('agency_type', sa.String(length=20), nullable=False),
    sa.Column('representative_name', sa.String(length=100), nullable=True),
    sa.Column('business_number', sa.String(length=20), nullable=True),
    sa.Column('business_email', sa.String(length=254), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_image_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('approval_status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('subscription_type', sa.String(length=20), server_default=sa.text("'FREE'"), nullable=False),
    sa.Column('ai_recommend_enabled', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('casting_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('successful_match_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("agency_type IN ('AGENCY','PRODUCTION','BRAND','CASTING')", name='ck_agency_master_agency_type'),
    sa.CheckConstraint("approval_status IN ('PENDING','APPROVED','REJECTED')", name='ck_agency_master_approval_status'),
    sa.CheckConstraint("subscription_type IN ('FREE','BASIC','PREMIUM')", name='ck_agency_master_subscription_type'),
    sa.PrimaryKeyConstraint('agency_id'),
    sa.UniqueConstraint('business_number')
    )
    op.create_table('agency_member',
    sa.Column('agency_member_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('role_code', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position_name', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_master.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agency_id'], ['agency_master.agency_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agency_member_id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('talent_master',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('gender_self_description', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('region_code', sa.String(length=20), nullable=True),
    sa.Column('main_category', sa.String(length=20), nullable=True),
    sa.Column('sub_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.SmallInteger(), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('tiktok_url', sa.String(length=500), nullable=True),
    sa.Column('career_level', sa.String(length=20), nullable=True),
    sa.Column('visibility_status', sa.String(length=20), server_default=sa.text("'PRIVATE'"), nullable=False),
    sa.Column('approval_status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('profile_completion_rate', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('ai_match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profile_view_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('favorite_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('casting_apply_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("approval_status IN ('PENDING','APPROVED','REJECTED')", name='ck_talent_master_approval_status'),
    sa.CheckConstraint("career_level IS NULL OR career_level IN ('NEWBIE','PRO')", name='ck_talent_master_career_level'),
    sa.CheckConstraint("gender IS NULL OR gender IN ('MALE','FEMALE','SELF_DESCRIBED')", name='ck_talent_master_gender'),
    sa.CheckConstraint("main_category IS NULL OR main_category IN ('ACTOR','MODEL','INFLUENCER','VOCAL','DANCER','MC','CREATOR')", name='ck_talent_master_main_category'),
    sa.CheckConstraint("region_code IS NULL OR region_code IN ('SEOUL','BUSAN','INCHEON','DAEGU','DAEJEON','GWANGJU','ULSAN','SEJONG','GYEONGGI','GANGWON','CHUNGBUK','CHUNGNAM','JEONBUK','JEONNAM','GYEONGBUK','GYEONGNAM','JEJU')", name='ck_talent_master_region_code'),
    sa.CheckConstraint("visibility_status IN ('PUBLIC','PRIVATE')", name='ck_talent_master_visibility_status'),
    sa.CheckConstraint('profile_completion_rate >= 0 AND profile_completion_rate <= 100', name='ck_talent_master_completion_rate'),
    sa.ForeignKeyConstraint(['account_id'], ['account_master.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talent_master')
    op.drop_table('agency_member')
    op.drop_table('agency_master')
    # ### end Alembic commands ###
