"""add account_master deactivated_at and deactivation_reason

Revision ID: dffcca6577c6
Revises: 7863df88d288
Create Date: 2026-05-29 14:51:20.040368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffcca6577c6'
down_revision: Union[str, Sequence[str], None] = '7863df88d288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_master', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('account_master', sa.Column('deactivation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_master', 'deactivation_reason')
    op.drop_column('account_master', 'deactivated_at')
    # ### end Alembic commands ###
