"""add talent_master profile_image_urls (jsonb array)

Revision ID: ff7c8b02a52c
Revises: 84a9bf97e3d3
Create Date: 2026-05-29 16:14:27.430656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff7c8b02a52c'
down_revision: Union[str, Sequence[str], None] = '84a9bf97e3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talent_master', sa.Column('profile_image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talent_master', 'profile_image_urls')
    # ### end Alembic commands ###
